language: c
env:
  global:
  - PHARO_VERSION=50
  - secure: V5UnNF7LHqaBVzfjMkdQpiUCemUhKjm07KMEmfPkAuEsK1czoK/ZM3cGtmiIW5Ul86qvMjdXfsz6URCEsFpdb6W4EXzcwJmtxgJjvaC3NJcvNNUgt+uPU3yokwGuYIrdmlVcO73kMrk3trezexen4EXrPQjR3yUrLCXdSXJ1j97AxnT5drCLuBXAaw9W6QiHInWRE9UMIP+CY5c0EsH4JZy6uqAArWzY74fKawr7lOafLA9AzlCGE87q9N5SeUwKIgSSz9AuctAX0o+LoTKegDtMGLOaGtFFCCwgkGgZfAh3dXBut60F8uglmRWcUb0M3+9VWljmDfbLoupMFn2KQFNn+Guap9O2efeelkcpubp2/rXC0QXuLLBPfUyRyKQIOK06jBVz5NxJzUQvv7Yae1fv/R6qB2DSgK6+bF8QGwdZ8AXROmZ75sJc9mR26VRirm8MtTr5xEpDJ4ldLQo9rZUF8x6+pnhBM42wgbRMXcjbxngb1pO5NUjgAHZk7Ri09ZAXUUu5+FLwrn1NSN5UDn4AjmUipK0mwvab/IS7TmpQGh3DoFk2YUCgrVdlFCw/h8kel0EivhG2zXC1UJUXn6gAek1VuuHfdh2vR8/WbNmcdPFxG7oQiJb9hVhVkvgNdltkAPzKueVOpmGhWeVHXUdtQWoGX04doxvu3KRJAvQ=
  - secure: PZRpRbQp1R0UnowYqgp56ttMMTTB4SpL7DrougKPVNFopAz7eA6yvPl4Q5l9kXdHh2RTd60PHV4nmnlBCJi21kRxSHUYzCT+Pe7rymjnp2jj3JtnZe9WbD+s5PKr5lQ1MzEKNEws/lUXCWMCSHNaa8GBbS5UQncLkvxGM1hCKsMuEtzGUKiFTmbrPGe3wcJoD2ToPh8PPrldbjJvVyWmWjTqqh/IEW9d76M/2F1ZbbMlE7hF0Psk550QkvsvLZHIsymIu/HQouXZp+TSSnv0tj/VAFm8uicvthz/B8wZ25M3zChiLqnRoxOeKKYeQSnm5v+oHIuE3Xg7Ewlh8hJk/7fEP2A1fFZPDX3vCBfjcW4ewOe8mhAtnlyvWu0clRZbZ1rQWDZuLZOVFTAtDVKeYnYrNVbrE+Jso+/1/eOYNtau8pr5RBvA7jMCR3QhDgpk5SsqzlmUjZgrQiJxxnCy64pdDwasRapc6eHKXRq8Dqh+WHF5Sc2Br6IP7sY/tW4AltJ+sBVhdQM4/zPZCubohJy/7d2bytbtHytYt0U1T584E9uDVeprnlhl+tW/FxcAuYP5coKqhN4FYs3UMl70iOFN8/0FYKKQJq0BXVUJuD/pWqFssuLKAGCjHvnWJJ2Lw4zAcUXzkRRXAyzNjOZg8oO4wCW/gz4ZC3U8nlMsAPk=
  - secure: QQNyWAyPqIrZiRSIUJE8p0x4Zu4HTp45ruy8y4K/4NM30sarvg/CXqHRw/5ufB3vkdkbwoyzsgVKHv6u8lLg6Twokridi9tZOohh7RiWY6PTfOkcLx92O2yJ8V92FH6m9KStkg0hagB3eN11IS0l7Bi3XnlEUTObPsrCFL/Tqgt2Vx4CQmlcYH/g2GFWX8mlCoGMmzOSOSs8md6ws0/h4wmA6UQraZgPWPXgvLHkVkKeut9Tc+IqU0hBDBNm1iOCaivze53mxTkEW/LCuogfY/lyOIiKiRKCmtm4v/h9sW59QuNiD3XLBAxbVbbmbg6B2tOGM640B6HBr6a5toFEmQC3PN3Mct1guRSiMkZlx/mo92+Xt/6keUvZ3joeHQgkltlRm4EmCKp9UX51bI74rRM+A/PMGk6POuWzbLEp2On8Rr1CNxxSQKCVC0Q1dsjiVvMnvn4iABLqO8fMl4TSs+O9AC3k9AL89mvED9ga3VIlZR/GnFtWxlGFtErHnPAYu0GIJRJENSsjne7NruwfyE3+/2YoeSJqVSd2eEbkm5q2LH9Ej8vat8eQgwoYoV+jc8pi/LkajpnygEPr7Sa8XODGyKWS1OmBNFWZZGEFt+Gt5pRQhTV5s5RES9hoTgFDNMJR6SQlCeKDdFrpq8zOByfXJmsCRQ15fgFZXKTRw8I=
  - secure: i2ZkpSOg1j8fKfaYnpAsWiLMMz7QERaQZKeSF3K1XkZqt6Heb/K2BP0SL86dej4f3iEqYstHL/79OtdLjegMS2tvKDS7wCQY+Dr9wyuzWa/Zhhkgyp5vGo+u/Xie/SxUBvF9J19XXnol4sgqI4xXGRPqy8pTSyqSyghjZeA3GqQD9jJzdGhXZXjgReHWIwsHdilRqRZnXfASyEM844WDvo5y2QNLAj1kfw/aNgU8ABafGs6cfIg4OcEzoB/SHI4PnOvLCs9oQfsOQjsft8/90QNghsFNF416akgWgm8LrK45ymgOeVjsqfRpgjZ2qVT07sUBIDQrSCbIW9qTL1+MGALjxvuzsRfgFf8XOwFnJJgU5vBF1RgRbGXC2c9IVHZJ2i7xVaMiL1osOuf+QnvowlFMtJe4xpPvYAiYUnKL727XRrv6PXSKpZTJy6Qjzr4WMtT0UL/JAWfa3VGug61c/eDoauiwvELsz6X3NjkxXqGxDVv5lg5NO09a+Sw7TXj/KuFIUuLefVLYa+1VZHZlKW1VJ18PR/ZkHVNdCeNT9DHiStM+AXFlVue3cLFiKOmu7r4fdK5ZbefAqm2PQOH01WIGL0WY+r1GaneBAISfcCc4uK52AYsaBeKBgO5CM6du9F1WZUXxVg/rXoU4SSEIG+2MyfXla/EzjuZL6YtS+9k=
  matrix:
  - BOOTSTRAP_ARCH=32 BOOTSTRAP_DISTIRBUTION=default
  - BOOTSTRAP_ARCH=64 BOOTSTRAP_DISTIRBUTION=default
  - BOOTSTRAP_ARCH=32 BOOTSTRAP_DISTIRBUTION=minimal
  - BOOTSTRAP_ARCH=64 BOOTSTRAP_DISTIRBUTION=minimal

addons:
  apt:
    packages:
    - lib32asound2
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386

install:
 - "wget -O - get.pharo.org/${PHARO_VERSION}+vm | bash"
# - "./scripts/install-packages.sh"
 
script:
 - "./pharo Pharo.image ./scripts/bootstrap.st" # ${BOOTSTRAP_VERSION} ${BOOTSTRAP_ARCH} ${BOOTSTRAP_DISTIRBUTION}"
 - "zip -r bootstrap bootstrap.image" # boot-packages"
 - #"./scripts/dropbox_upload.sh upload bootstrap.zip bootstrap-${BOOTSTRAP_VERSION}-${BOOTSTRAP_ARCH}-${BOOTSTRAP_DISTIRBUTION}-${TRAVIS_JOB_NUMBER}.zip"